apiVersion: v1
kind: Pod
metadata:
  name: nginx #name of pod
  labels:
    app: nginx #use this label to expose on service 
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80